[build]
  command = "echo 'No build required'"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[context.production]
  command = "echo 'Production build'"

[context.deploy-preview]
  command = "echo 'Preview build'"